### ISSUE TITLE
Voting-Poll-LastChanges

### ISSUE THREAD

**Issue by estefaninoely** [devhausleipzigacademy/camp9-final-project#114]
- [x] add navabar 
- [x] remove description if it's empty 
- [x] fix answers 
- [x] padding for the scrollbar should keep in 2px 
- [x] change radio button to be checkbox but with the logic of radio button 
- [x] add a tostify message to avoid double votes in query handler 
- [x] clean errors , console.log and extra importations or types

**Comment by intertemp** [comment]
done
