### ISSUE TITLE
Shared Button Components

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-final-project#12]
Create all needed Button components for your App. Think about which props are needed. 
Do you have different color variants? Do you have different sizes? Don't forget to pass the props for the event handler.

Make sure you have a clean folder structure. Also show all Buttons and Variants in storybook

- [x] write all Button components you will need for ur app. (forward, back -button, Icon Button, TextButton....)
- [x] Setup props, dont forget the event handler prop.
- [x] Setup storybook if not done
- [x] write a storybook story for your Buttons

**Comment by manuelpastorringuelet** [comment]
Button and TabButton finished

**Comment by manuelpastorringuelet** [comment]
Button and TabButton finished
