### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-final-project#14]
Create the component for the bottom Navbar. Buttons for the Navbar should be already created.
Dont forget the routing to link to a specific page.

- [x] create Navbar component
- [x] dont forget the routing for the link items
- [x] setup active state for the navbar
- [x] write story for the navbar

**Comment by estefaninoely** [comment]
all the component and story is done. for now is just a # indicating the href (link to different page) for each button. waiting for the pages to link.
