### ISSUE TITLE
User Setting

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-final-project#145]
The inputfields are not disabled at all. The entire save and update logic is broken.

The last working commit is:
https://github.com/devhausleipzigacademy/camp9-final-project/commit/aa5bee7c062126c4fa0f3056a4e195ee8afacd1b

**Comment by intertemp** [comment]
fixed issue with disabled not working on settings. disabled was in the extended type but was used as disabled within the components. changed it to props.disabled, which fixed it
