### ISSUE TITLE
login user

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-final-project#17]
Setup the whole logic which is needed to login a user. Implement the UI and also the needed logic for backend and frontend.

- [x] Create Login Page (input fields and buttons should already be created)
- [x] write a submit handler and get the values from the form fields
- [x] implement frontend validation for the input fields and the given form with zod and react-hook-forms (read the docs. ask for help if needed)
- [x] send the data via react query mutation to the backend
- [x] create route handler for the req.
- [x] implement backend validation via zod
- [x] use next-auth package with credentials provider (or any provider u wanna use google, twitter etc)
- [x] install and use the prisma adapter for next-auth package
- [x] change user prisma model so it fits the credentials for the prisma adapter
- [x] use the onSucces and onError handler from react query to show a toast message (link below) 

Links: 
https://react-hook-form.com/
https://www.npmjs.com/package/react-toastify

**Comment by DougInAMug** [comment]
completed without adapter
