### ISSUE TITLE
Create Poll Form

### ISSUE THREAD

**Issue by verascheunert** [devhausleipzigacademy/camp9-final-project#27]
- [ ] Finish design (if necessary)

Implement all the form steps

- [x] Question/Title, description
- [ ] Poll type
- [ ] Reveal conditions
- [ ] Deadline type
- [ ] Add participants
- [ ] Submit & review
- [ ] Submit the poll and make sure the data is stored in the db 
- [ ] add error handling to the non optional input fields

- [x] Find Countdown Clock and Calendar

**Comment by Quenayalui** [comment]
https://excalidraw.com/#json=nz66lID3LwRMuh1LQ0RNj,b1NEm814JJ8-ZXN8kDAzNg

notes on how to configure the creating-poll-pages
