### ISSUE TITLE
Create User Settings

### ISSUE THREAD

**Issue by verascheunert** [devhausleipzigacademy/camp9-final-project#28]
- [x] Create User Settings Page
- [x] Add link in the navbar 
- [x] Create edit button component and check mark

Change Password & username
- [x] Add input fields 
- [x] Add logout button 
- [x] Error handling (valid password/username)
- [x] Success notification

**Comment by DougInAMug** [comment]
Hey, shall I help with the backend connection? Can you push a branch for me?
