### ISSUE TITLE
Create Poll Results Pages

### ISSUE THREAD

**Issue by suzydevhaus** [devhausleipzigacademy/camp9-final-project#52]
These are the screens that show that poll details of a poll that has finished (the deadline has been reached). These screen are shown when clicking on a poll card from the 'closed' tab in the home screen.

- [x] Display poll details from the backend
- [x] Build square card component
- [x] Show the votes in absolute counts
- [ ] make pop-up for showing the participants that voted
- [x] Show the votes in relatives counts (for percentage bar)
- [x] create component "poll results card"
- [x] Add Progress Bar Component (in 52-doug)
- [x] Add custom Scrollbar (merged-work)
- [x] display right checkboxes
- [x] implement Mood functionality (in 52-doug)
- [x] fix styling (see `results/10`)
- [x] fix question slicing (see `results/10`)

Base off of "Poll results" in figma

**Comment by NnekNnek** [comment]
I added the task : create component "poll results card"

**Comment by morascode** [comment]
Hey I think a lot of data parsing stuff for this page is similiar to what I did in poll details, lmk if you need some help with it!

**Comment by DougInAMug** [comment]
Not everything done, but most of it - and merged to main. Closing this issue, let's do followup in separate issues :)

Was fun working on this one with you @NnekNnek  :+1:
